apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: shop-activity
scopes:
  - order-manager
  - inventory-service
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
