apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalyst-demo-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/diagrid-labs/catalyst-order-workflow-dotnet
    targetRevision: main
    path: k8s/infra
  destination:
    server: https://kubernetes.default.svc
    namespace: catalyst-order-workflow-demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
