apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
- name: argo-cd
  repo: oci://ghcr.io/argoproj/argo-helm
  version: 9.4.7
  releaseName: argocd
  includeCRDs: true
  valuesInline:
    controller:
      replicas: 1
    server:
      replicas: 1
    repoServer:
      replicas: 1
    applicationSet:
      enabled: false 
    notifications:
      enabled: false 
    dex:
      enabled: false 
    redis-ha:
      enabled: false
    crds:
      install: true 
      keep: true
    configs:
      repositories:
        catalyst-order-workflow:
          url: https://github.com/diagrid-labs/catalyst-order-workflow-dotnet
